apiVersion: 1

datasources:
  - name: Mimir
    uid: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
